//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutterLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MutterLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ARW07DN {
            get {
                object obj = ResourceManager.GetObject("ARW07DN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ARW07UP {
            get {
                object obj = ResourceManager.GetObject("ARW07UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Ctrpanel {
            get {
                object obj = ResourceManager.GetObject("Ctrpanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Ctrpanel16 {
            get {
                object obj = ResourceManager.GetObject("Ctrpanel16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Mutter Launcher .NET is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrDuplexRun {
            get {
                return ResourceManager.GetString("ErrDuplexRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SPACE is not permitted for EndWith-char. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrEndWithSpace {
            get {
                return ResourceManager.GetString("ErrEndWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a ascii char. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotAscii {
            get {
                return ResourceManager.GetString("ErrNotAscii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not support to open dir. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotSupportOpenDir {
            get {
                return ResourceManager.GetString("ErrNotSupportOpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is not support to run as administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotSupportRunAsAdmin {
            get {
                return ResourceManager.GetString("ErrNotSupportRunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a valid value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNumericRange {
            get {
                return ResourceManager.GetString("ErrNumericRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a numeric value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNumericVal {
            get {
                return ResourceManager.GetString("ErrNumericVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot read: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRead {
            get {
                return ResourceManager.GetString("ErrRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot register Hot-Key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrRegHotkey {
            get {
                return ResourceManager.GetString("ErrRegHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a valid key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrSettingHotkey {
            get {
                return ResourceManager.GetString("ErrSettingHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a command. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUserItemCmd {
            get {
                return ResourceManager.GetString("ErrUserItemCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a valid encoding. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUserItemEncoding {
            get {
                return ResourceManager.GetString("ErrUserItemEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set a name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrUserItemName {
            get {
                return ResourceManager.GetString("ErrUserItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot write: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrWrite {
            get {
                return ResourceManager.GetString("ErrWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap mutter {
            get {
                object obj = ResourceManager.GetObject("mutter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon MutterIco {
            get {
                object obj = ResourceManager.GetObject("MutterIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon RefreshIco {
            get {
                object obj = ResourceManager.GetObject("RefreshIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
